---
title: "Shinny App Presentation"
author: "Caroline Bressan"
format: revealjs
editor: visual
---

## Shinny Application Project

This peer assessed assignment has two parts. First, you will create a Shiny application and deploy it on Rstudio's servers. Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

 - The Shiny Application

-   Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application.

-   Deploy the application on Rstudio's shiny server

-   Share the application link by pasting it into the provided text box

\- The Reproducible Pitch Presentation

-   5 slides (inclusive of the title slide) to pitch a the app.

-   Create a web page using Slidify or Rstudio Presenter with an html5 slide deck.

-   The presentation must be pushed to github or Rpubs

-   A link to the github or Rpubs presentation pasted into the provided text box.

## Plotting Random Numbers

In this App you will plot random numbers, choosing the numbers trough the slider of the x and y coordinates.

And the plot will be shown instantly for you.

## **Shinny App**

## [https://carolineb.shinyapps.io/myApp/](https://carolineb.shinyapps.io/myApp/){#9273539}
